server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/china_epidemic?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  main:
    lazy-initialization: false
  redis:
    port: 6379
    password: 123456
    host: 192.168.80.228
    jedis:
      pool:
        max-idle: 6
        max-active: 10
        min-idle: 2
    timeout: 2000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pojo
  configuration:
    map-underscore-to-camel-case: true